export const AUTH_WATCHER = 'AUTH_WATCHER';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FALIURE = 'AUTH_FALIURE';

export const GET_DATA_WATCHER = "GET_DATA_WATCHER"
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS"
export const GET_DATA_FALIURE = "GET_DATA_FALIURE"