import {StyleSheet} from 'react-native';
import {Colors} from '../../common/styles/color';
import { horizontalScale } from '../../common/styles/styles';

export const styles = StyleSheet.create({
  mainBox: {flex: 1, backgroundColor: '#FFFFFF'},
  modal: {
    flex: 1,
    // justifyContent: 'center',
    // alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: horizontalScale(20),
    borderRadius: 10,
    alignItems: 'center',
    elevation: 5,
    marginHorizontal: horizontalScale(20),
    marginTop: horizontalScale(70)
  },
  filterContainer:{
    height: horizontalScale(70),
    width: '100%',
    alignItems:'center',
    flexDirection: 'column',
  },
  filterContain:{
    height: horizontalScale(60),
    width: '95%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent:'center'
  },
  filetView:{
    height: horizontalScale(35),
    borderWidth: 1,
    width: horizontalScale(130),
    borderRadius: horizontalScale(15),
    alignItems: 'center',
    justifyContent: 'center',
  },
  textFilter:{
    fontSize: horizontalScale(15),
    color: Colors.black,
  },
  modelContain:{
    height: horizontalScale(60),
    width: '100%',
    flexDirection: 'column',
  },
  itemConainer:{
    height: horizontalScale(60),
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  itemContain:{
    height: horizontalScale(35),
    // width: horizontalScale(100),
    borderWidth: 1,
    borderRadius: horizontalScale(15),
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
},
modelText: {
    fontSize: horizontalScale(15),
    color: Colors.black,
  },
 modelItemShow: {
    height: horizontalScale(35),
    borderWidth: 1,
    borderRadius: horizontalScale(15),
    alignItems: 'center',
    justifyContent: 'center',
    padding: 5,
},
cloaseContainer:{
    height: horizontalScale(60),
    width: '95%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  closeModel: {
    height: horizontalScale(35),
    borderWidth: 1,
    width: horizontalScale(80),
    borderRadius: horizontalScale(15),
    alignItems: 'center',
    justifyContent: 'center',
  },
  applyModel: {
    height: horizontalScale(35),
    width: horizontalScale(100),
    borderWidth: 1,
    borderRadius: horizontalScale(15),
    alignItems: 'center',
    marginHorizontal: horizontalScale(5),
    justifyContent: 'center',
    backgroundColor: '#EF6041',
  },
  flatlistMain:{
    marginHorizontal: horizontalScale(15),
    marginVertical: horizontalScale(10),
    borderRadius: horizontalScale(20),
    height: horizontalScale(400),
    overflow: 'hidden',
    backgroundColor: Colors.semiGray,
    elevation: horizontalScale(10),
    shadowOpacity: horizontalScale(20),
    shadowRadius: horizontalScale(25),
  },
  flatlistconatin:{
    height: horizontalScale(230),
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
  },
  imageConatiner:{
    height: horizontalScale(200),
    width: horizontalScale(310),
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: horizontalScale(10),
    borderRadius: horizontalScale(10),
  },
  imageShow:{
    height: horizontalScale(150),
    width: horizontalScale(310),
    borderRadius: horizontalScale(10),
  },
  imagecount:{
    backgroundColor: Colors.black,
    height: horizontalScale(38),
    width: horizontalScale(75),
    borderRadius: horizontalScale(15),
    marginVertical: horizontalScale(10),
    alignItems: 'center',
    justifyContent: 'center',
  },
  pgrateConatiner:{
    height: horizontalScale(40),
    marginHorizontal: horizontalScale(15),
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  pgnameConatiner:{
    height: horizontalScale(55),
    marginHorizontal: horizontalScale(15),
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  pglocation:{
    height: horizontalScale(80),
    width: '90%',
    marginHorizontal: horizontalScale(15),
    justifyContent: 'flex-start',
    alignItems: 'center',
    flexDirection: 'row',
  }
});
